"""Add Webhook and Organizacion models for Fases 11-12

Revision ID: edd4dd3ea516
Revises: ad8e9bbb3a0e
Create Date: 2026-07-07 06:51:35.614386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd4dd3ea516'
down_revision = 'ad8e9bbb3a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizaciones_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizaciones_slug'), ['slug'], unique=True)

    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ultimo_envio', sa.DateTime(), nullable=True),
    sa.Column('ultimo_estado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_evento'), ['evento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_evento'))

    op.drop_table('webhooks')
    with op.batch_alter_table('organizaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizaciones_slug'))
        batch_op.drop_index(batch_op.f('ix_organizaciones_nombre'))

    op.drop_table('organizaciones')
    # ### end Alembic commands ###
